name: log_keep
description: LogKeep app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0

  firestore_cache: ^2.1.1

  tuple: ^2.0.0

  get_it: ^7.2.0

  proviso: ^1.0.5

  flutter_bloc: ^7.1.0

  dartz: ^0.10.0

  file_picker_cross: ^4.4.2

  fading_edge_scrollview: ^2.0.0

  rflutter_alert: ^2.0.4

  log_keep_shared:
    path: ../pkg/log_keep_shared

  cupertino_icons: ^1.0.3
  intl: ^0.17.0
  clipboard: ^0.1.3

  universal_html: ^2.0.8
  web_browser: ^0.5.0

  google_fonts: ^2.1.0

  uiblock: ^2.0.0

  equatable: ^2.0.3
  rxdart: ^0.27.1

  hovering: ^1.0.4

  logger: ^1.0.0

  hive: ^2.0.4
  path_provider: ^2.0.2

flutter:
  uses-material-design: true